services:
  sas_force_sensor:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID
    volumes:
      - ~/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: /bin/bash -c "
      cd /root/sas_force_sensor_devel/src/
      && ls .
      && colcon build
      && source install/setup.bash
      && ros2 run sas_force_sensor sas_force_sensor_interface_example.py"

  sas_force_sensor_gui:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID
    volumes:
      - ~/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: /bin/bash -c "
      sudo apt-get install -y xvfb
      && (sudo /usr/bin/Xvfb :99 -screen 0 1280x1024x24 &)
      && export DISPLAY=:99
      && cd /root/sas_force_sensor_devel/src/
      && ls .
      && colcon build
      && source install/setup.bash
      && ros2 run sas_force_sensor sas_force_sensor_gui"
